export const TRANSACTIONS = [
  {
    status: 'pending',
    type: 'tip',
    amount: 50,
    notes: 'Tip To Teacher',
    date: '2022-01-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 20,
    notes: 'Tip To Teacher',
    date: '2022-02-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 30,
    notes: 'Tip To Teacher',
    date: '2022-03-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 40,
    notes: 'Tip To Teacher',
    date: '2022-04-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 50,
    notes: 'Tip To Teacher',
    date: '2022-05-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 60,
    notes: 'Tip To Teacher',
    date: '2022-06-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 70,
    notes: 'Tip To Teacher',
    date: '2022-07-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 80,
    notes: 'Tip To Teacher',
    date: '2022-08-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 90,
    notes: 'Tip To Teacher',
    date: '2022-09-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 100,
    notes: 'Tip To Teacher',
    date: '2022-10-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 110,
    notes: 'Tip To Teacher',
    date: '2022-11-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 120,
    notes: 'Tip To Teacher',
    date: '2022-12-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 130,
    notes: 'Tip To Teacher',
    date: '2023-01-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 140,
    notes: 'Tip To Teacher',
    date: '2023-02-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 150,
    notes: 'Tip To Teacher',
    date: '2023-03-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 160,
    notes: 'Tip To Teacher',
    date: '2023-04-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 170,
    notes: 'Tip To Teacher',
    date: '2023-05-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 180,
    notes: 'Tip To Teacher',
    date: '2023-06-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 190,
    notes: 'Tip To Teacher',
    date: '2023-07-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 200,
    notes: 'Tip To Teacher',
    date: '2023-08-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 210,
    notes: 'Tip To Teacher',
    date: '2023-09-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 220,
    notes: 'Tip To Teacher',
    date: '2023-10-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 230,
    notes: 'Tip To Teacher',
    date: '2023-11-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 240,
    notes: 'Tip To Teacher',
    date: '2023-12-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 240,
    notes: 'Tip To Teacher',
    date: '2024-01-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 240,
    notes: 'Tip To Teacher',
    date: '2024-03-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 240,
    notes: 'Tip To Teacher',
    date: '2024-05-12',
  },
];
