export const TRANSACTIONS = [
  {
    status: 'pending',
    type: 'tip',
    amount: 100,
    notes: 'Tip To Teacher',
    date: '2023-08-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 100,
    notes: 'Tip To Teacher',
    date: '2023-07-12',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 100,
    notes: 'Tip To Teacher',
    date: '2023-06-12',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 150,
    notes: 'Tip To Teacher',
    date: '2023-05-13',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 30,
    notes: 'Tip To Teacher',
    date: '2023-04-14',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 100,
    notes: 'Tip To Teacher',
    date: '2023-03-12',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 150,
    notes: 'Tip To Teacher',
    date: '2023-02-13',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 30,
    notes: 'Tip To Teacher',
    date: '2023-01-14',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 100,
    notes: 'Tip To Teacher',
    date: '2022-12-12',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 150,
    notes: 'Tip To Teacher',
    date: '2022-11-13',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 30,
    notes: 'Tip To Teacher',
    date: '2022-10-14',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 100,
    notes: 'Tip To Teacher',
    date: '2022-09-12',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 150,
    notes: 'Tip To Teacher',
    date: '2022-08-13',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 30,
    notes: 'Tip To Teacher',
    date: '2022-07-14',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 100,
    notes: 'Tip To Teacher',
    date: '2022-06-12',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 150,
    notes: 'Tip To Teacher',
    date: '2022-05-13',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 30,
    notes: 'Tip To Teacher',
    date: '2022-04-14',
  },
  {
    status: 'pending',
    type: 'tip',
    amount: 100,
    notes: 'Tip To Teacher',
    date: '2022-03-12',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 150,
    notes: 'Tip To Teacher',
    date: '2022-02-13',
  },
  {
    status: 'succeeded',
    type: 'tip',
    amount: 30,
    notes: 'Tip To Teacher',
    date: '2022-01-14',
  },
];
